class NicolaySensor:
    current_baud_rate: int
    is_open: bool
    slave_address: int

    def __init__(self, port: str, slave_address: int = 0) -> None: ...
    def close(self) -> None: ...
    def get_flow_and_pressure(self) -> tuple[int, int]: ...
    def get_flow(self) -> int: ...
    def get_hw_version(self) -> dict[str, int]: ...
    def get_pressure(self) -> int: ...
    def get_sw_version(self) -> dict[str, int]: ...
    def set_uart_baud(self, baud_code: int) -> int: ...
